runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /(.*\.(gif|GIF|png|PNG|jpg|JPG|ico|ICO|js|JS|css|CSS))$
  static_files: dist/\1
  upload: dist/(.*)

- url: /(.*)$
  static_files: dist/index.html
  upload: dist/index.html